org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx3G

# Minecraft / Fabric
minecraft.version=1.21.11
fabric.loader.version=0.19.5
fabric.api.version=0.141.6+1.21.11

# Mod metadata
mod.name=voice-bridge
mod.group=io.pfaumc.voicebridge
mod.version=2.0.0-SNAPSHOT

# Dependencies
svc.api.version=2.6.0
plasmo.voice.version=2.1.8
